app/Http/routes.php
<?php

Route::get('/', 'PageController@index');
Route::get('blog', 'ArticleController@index');
Route::get('travel-security', 'ArticleController@travelSecurity');

Route::get('travel', 'PageController@travel');
Route::get('rafting', 'PageController@rafting2016');

Route::resource('article', 'ArticleController');
Route::get('random', 'ArticleController@random');

Route::get('tag/{tag}', 'TagController@show');

Route::controllers([
    'auth' => 'Auth\AuthController',
    'password' => 'Auth\PasswordController',
]);

Route::get('image/upload', 'ImageController@getUpload');
Route::get('image/generate', 'ImageController@getGenerateImages');
Route::post('image/upload', 'ImageController@postUpload');

resources/views/partials/nav.blade.php
<nav class="navbar navbar-static-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">
                Pavel Rybakov - Software development
            </a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">

            </ul>
            @if (Auth::check())
            <ul class="nav navbar-nav navbar-right">
                <li><a href="https://www.facebook.com/pavel.rybako" target="_blank">Contact</a></li>
                <li><a href="/">{{ Auth::user()->name }}</a></li>
                <li><a href="{{route('article.create')}}" title="добавить статью">Добавить статью</a></li>
                <li>{!! link_to('auth/logout', 'Выйти') !!}</li>
            </ul>

            @else
            <ul class="nav navbar-nav navbar-right">
                <li>
                    {!! link_to('blog', 'Blog') !!}
                </li>
                <li>
                    <a href="https://www.facebook.com/pavel.rybako" target="_blank">Contact me</a>
                </li>
            </ul>
            @endif
        </div>

    </div>
</nav>

{{--
<script type="text/javascript">
    function googleTranslateElementInit() {
        new google.translate.TranslateElement({pageLanguage: 'ru', includedLanguages: 'de,en,es,th,zh-CN', layout: google.translate.TranslateElement.InlineLayout.SIMPLE, multilanguagePage: true, gaTrack: true, gaId: 'UA-29199759-6'}, 'google_translate_element');
    }
</script>
<script type="text/javascript" src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"></script>--}}

resources/views/partials/tickets_form.blade.php
<script charset="utf-8" src="//www.travelpayouts.com/widgets/b069f843166d15df922ade4e824fca00.js?v=693" async></script>